import type { App } from '../index';
import { esc, tg, log } from '../lib/helpers';
import { layout } from '../views/html';
export function registerBotsRoutes(app: App) {
app.get('/bots',async c=>{const q=new URL(c.req.url).searchParams.get('q')||'';const rows:any[]=await c.env.DB.prepare(`SELECT b.*, (SELECT COUNT(*) FROM telegram_users u WHERE u.bot_id=b.id) user_count FROM bots b WHERE b.name LIKE ? OR COALESCE(b.username,'') LIKE ? ORDER BY b.id DESC`).bind(`%${q}%`,`%${q}%`).all().then(x=>x.results as any[]);return c.html(layout('Botlar',`<div class="actions"><form style="flex:1" method="get"><input class="input" name="q" value="${esc(q)}" placeholder="Bot ara..."></form><a class="btn" href="/bots/add">+ Bot Ekle</a><form method="post" action="/bots/check-all"><button class="btn gray">Tüm Botları Kontrol Et</button></form></div><br><div class="card scroll"><table class="table"><tr><th>Bot</th><th>Kullanıcı</th><th>Durum</th><th>Telegram</th><th>İşlem</th></tr>${rows.map(b=>`<tr><td><a href="/bots/${b.id}"><b>${esc(b.name)}</b></a><br><span class="muted">@${esc(b.username||'-')}</span></td><td>${b.user_count}</td><td><span class="pill ${b.status?'':'off'}">${b.status?'Aktif':'Pasif'}</span></td><td>${b.last_error?`<span class="danger">Hata</span>`:'OK'}</td><td><div class="actions"><a class="btn gray" href="/bots/${b.id}">Yönet</a><form method="post" action="/bots/${b.id}/toggle"><button class="btn gray">${b.status?'Pasifleştir':'Aktifleştir'}</button></form></div></td></tr>`).join('')}</table></div>`))})
app.get('/bots/bulk-add',c=>c.html(layout('Toplu Bot Ekle',`<div class="card"><form class="form" method="post" action="/bots/bulk-add"><label>Bot tokenları</label><textarea class="input" name="tokens" rows="14" placeholder="Her satıra bir Telegram BotFather tokenı yazın"></textarea><button>Botları Doğrula ve Ekle</button></form><p class="muted">Her satırdaki token Telegram API üzerinden doğrulanır. Geçersiz veya daha önce eklenmiş tokenlar atlanır.</p></div>`)))
app.post('/bots/bulk-add',async c=>{
  try {
    const f=await c.req.parseBody();
    const raw=String(f.tokens||'');
    const tokens=[...new Set(raw.split(/[\r\n,;\t ]+/).map(x=>x.trim()).filter(Boolean))].slice(0,100);
    if(!tokens.length) return c.html(layout('Toplu Bot Ekle',`<div class="notice">En az bir token gir.</div><a class="btn" href="/bots/bulk-add">Geri dön</a>`),400);
    let added=0,failed=0,duplicate=0,dbErrors=0; const details:string[]=[];
    for(const token of tokens){
      if(token.length<20 || !token.includes(':')) { failed++; details.push(`${token.slice(0,7)}…: Token biçimi geçersiz`); continue; }
      const exists:any=await c.env.DB.prepare('SELECT id FROM bots WHERE token=?').bind(token).first();
      if(exists){ duplicate++; continue; }
      let r:any; try { r=await tg(token,'getMe'); } catch { failed++; details.push(`${token.slice(0,7)}…: Telegram API bağlantı hatası`); continue; }
      if(!r?.ok || !r?.result?.id){ failed++; details.push(`${token.slice(0,7)}…: ${r?.description||'Telegram doğrulaması başarısız'}`); continue; }
      try {
        await c.env.DB.prepare('INSERT INTO bots(name,username,token,telegram_id,description,short_description,last_checked_at,status,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(r.result.first_name||r.result.username||'Telegram Bot',r.result.username||'',token,r.result.id,'','',new Date().toISOString(),1,new Date().toISOString()).run();
        added++;
      } catch(e) {
        const msg=String((e as any)?.message||e);
        if(/unique|constraint/i.test(msg)){ duplicate++; } else { dbErrors++; details.push(`${token.slice(0,7)}…: Veritabanı hatası (${msg.slice(0,160)})`); }
      }
    }
    try { await log(c,'BULK_BOT_ADD',`read=${tokens.length} added=${added} failed=${failed} duplicate=${duplicate} dbErrors=${dbErrors}`); } catch {}
    return c.html(layout('Toplu Bot Ekle Sonucu',`<div class="grid"><div class="card stat">İşlenen<b>${tokens.length}</b></div><div class="card stat">Eklenen<b>${added}</b></div><div class="card stat">Geçersiz<b>${failed}</b></div><div class="card stat">Tekrar<b>${duplicate}</b></div></div><br><div class="card">${dbErrors?`<div class="notice">${dbErrors} veritabanı hatası oluştu. Aşağıdaki ayrıntı sorunun hangi sütun/tabloyla ilgili olduğunu gösterir.</div>`:''}${details.length?`<h3>Sonuç ayrıntıları</h3><pre style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(details.join('\n'))}</pre>`:'<p>İşlem tamamlandı.</p>'}<a class="btn" href="/bots">Botlara dön</a> <a class="btn gray" href="/bots/bulk-add">Tekrar dene</a></div>`));
  } catch(e) {
    return c.html(layout('Toplu Bot Ekle Hatası',`<div class="notice">Toplu ekleme sırasında sunucu hatası oluştu.</div><pre style="white-space:pre-wrap;overflow-wrap:anywhere">${esc((e as any)?.message||e)}</pre><p class="muted">Bu ayrıntıyı geliştiriciye iletebilirsin. Tokenlar gösterilmez.</p><a class="btn" href="/bots/bulk-add">Geri dön</a>`),500);
  }
})
app.get('/bots/add',c=>c.html(layout('Bot Ekle',`<div class="card"><form class="form" method="post" action="/bots/add"><input class="input" name="token" placeholder="Telegram Bot Token" required><input class="input" name="name" placeholder="Panel adı (boş bırakılırsa Telegram adı kullanılır)"><button>Telegram'dan Doğrula ve Ekle</button></form><p class="muted">Tokenı sadece panelde kullan. Sohbete token gönderme.</p></div>`)))
app.post('/bots/add',async c=>{const f=await c.req.parseBody(),token=String(f.token||'').trim(),custom=String(f.name||'').trim();if(!token)return c.text('Token gerekli',400);const r:any=await tg(token,'getMe');if(!r.ok)return c.html(layout('Bot Ekle',`<div class="notice">Telegram doğrulaması başarısız: ${esc(r.description)}</div>`),400);try{await c.env.DB.prepare('INSERT INTO bots(name,username,token,telegram_id,description,short_description,last_checked_at) VALUES(?,?,?,?,?,?,?)').bind(custom||r.result.first_name||r.result.username||'Telegram Bot',r.result.username||'',token,r.result.id,'','',new Date().toISOString()).run();await log(c,'BOT_ADD',`@${r.result.username||r.result.id}`);return c.redirect('/bots')}catch(e){return c.html(layout('Bot Ekle',`<div class="notice">Bot eklenemedi. Token daha önce eklenmiş olabilir.</div>`),400)}})
app.post('/bots/check-all',async c=>{const rows:any[]=await c.env.DB.prepare('SELECT id,token,username,telegram_id,status FROM bots').all().then(x=>x.results as any[]);let online=0,offline=0;for(const b of rows){let r:any;try{r=await tg(b.token,'getMe')}catch{r={ok:false,description:'Telegram API bağlantı hatası'}};const now=new Date().toISOString();await c.env.DB.prepare('UPDATE bots SET last_checked_at=?,last_error=?,username=?,telegram_id=?,status=CASE WHEN ?=1 THEN status ELSE 0 END,updated_at=? WHERE id=?').bind(now,r.ok?null:(r.description||'Telegram error'),r.ok?(r.result.username||''):b.username,r.ok?r.result.id:b.telegram_id,r.ok?1:0,now,b.id).run();if(r.ok)online++;else offline++;}await log(c,'CHECK_ALL',`total=${rows.length} online=${online} offline=${offline}`);return c.html(layout('Kontrol Sonucu',`<div class="grid"><div class="card stat">Toplam<b>${rows.length}</b></div><div class="card stat">Telegram'da geçerli<b>${online}</b></div><div class="card stat">Hatalı / erişilemeyen<b>${offline}</b></div></div><br><div class="notice">Geçerli botların açık/kapalı panel durumu korunur. Telegram'da geçersiz olanlar pasife alınır.</div><a class="btn" href="/bots">Botlara dön</a>`))})
app.post('/bots/:id/toggle',async c=>{const id=Number(c.req.param('id'));await c.env.DB.prepare('UPDATE bots SET status=CASE WHEN status=1 THEN 0 ELSE 1 END,updated_at=? WHERE id=?').bind(new Date().toISOString(),id).run();await log(c,'BOT_TOGGLE',String(id));return c.redirect('/bots')})
app.post('/bots/:id/check',async c=>{const id=Number(c.req.param('id'));const b:any=await c.env.DB.prepare('SELECT * FROM bots WHERE id=?').bind(id).first();if(!b)return c.text('Not found',404);const r:any=await tg(b.token,'getMe');await c.env.DB.prepare('UPDATE bots SET last_checked_at=?,last_error=?,username=?,telegram_id=?,updated_at=? WHERE id=?').bind(new Date().toISOString(),r.ok?'':String(r.description||'Telegram error'),r.ok?(r.result.username||''):b.username,r.ok?r.result.id:b.telegram_id,new Date().toISOString(),id).run();await log(c,'BOT_CHECK',`${id}:${r.ok?'OK':'FAIL'}`);return c.redirect(`/bots/${id}`)})
app.post('/bots/:id/delete',async c=>{const id=Number(c.req.param('id'));await c.env.DB.prepare('DELETE FROM bots WHERE id=?').bind(id).run();await log(c,'BOT_DELETE',String(id));return c.redirect('/bots')})
app.post('/bots/:id/refresh',async c=>{const id=Number(c.req.param('id'));const b:any=await c.env.DB.prepare('SELECT * FROM bots WHERE id=?').bind(id).first();if(!b)return c.text('Not found',404);const r:any=await tg(b.token,'getMe');if(!r.ok){await c.env.DB.prepare('UPDATE bots SET last_error=?,last_checked_at=? WHERE id=?').bind(r.description||'Telegram error',new Date().toISOString(),id).run();return c.redirect(`/bots/${id}`)}await c.env.DB.prepare('UPDATE bots SET name=?,username=?,telegram_id=?,last_error=NULL,last_checked_at=?,updated_at=? WHERE id=?').bind(r.result.first_name||b.name,r.result.username||'',r.result.id,new Date().toISOString(),new Date().toISOString(),id).run();await log(c,'BOT_REFRESH',String(id));return c.redirect(`/bots/${id}`)})
app.post('/bots/:id/webhook/set',async c=>{const id=Number(c.req.param('id'));const b:any=await c.env.DB.prepare('SELECT * FROM bots WHERE id=?').bind(id).first();if(!b)return c.text('Not found',404);const f=await c.req.parseBody();const supplied=String(f.url||'').trim();const origin=new URL(c.req.url).origin;const url=supplied||`${origin}/telegram/webhook/${id}`;if(!url.startsWith('https://')){await c.env.DB.prepare('UPDATE bots SET last_error=? WHERE id=?').bind('Webhook URL HTTPS olmalı',id).run();return c.redirect(`/bots/${id}`)}const r:any=await tg(b.token,'setWebhook',{url,allowed_updates:['message','edited_message','my_chat_member']});await c.env.DB.prepare('UPDATE bots SET webhook_url=?,last_error=?,updated_at=? WHERE id=?').bind(r.ok?url:b.webhook_url,r.ok?null:(r.description||'Webhook error'),new Date().toISOString(),id).run();await log(c,'WEBHOOK_SET',`${id}:${r.ok?'OK':r.description||'FAIL'}`);return c.redirect(`/bots/${id}`)})
app.post('/bots/:id/webhook/delete',async c=>{const id=Number(c.req.param('id'));const b:any=await c.env.DB.prepare('SELECT * FROM bots WHERE id=?').bind(id).first();if(!b)return c.text('Not found',404);const r:any=await tg(b.token,'deleteWebhook');await c.env.DB.prepare('UPDATE bots SET webhook_url=NULL,last_error=? WHERE id=?').bind(r.ok?null:(r.description||'Webhook error'),id).run();return c.redirect(`/bots/${id}`)})
}
