import type { App } from '../index';
import { esc, tg, log } from '../lib/helpers';
import { layout } from '../views/html';
export function registerCommandsRoutes(app: App) {
app.get('/bots/:id/commands',async c=>{const id=Number(c.req.param('id'));const b:any=await c.env.DB.prepare('SELECT * FROM bots WHERE id=?').bind(id).first();if(!b)return c.text('Bot bulunamadı',404);const rows:any[]=await c.env.DB.prepare('SELECT command,description,response_text FROM bot_commands WHERE bot_id=? ORDER BY command').bind(id).all().then(x=>x.results as any[]);const value=rows.map(x=>`${x.command} | ${x.description} | ${x.response_text||''}`).join('\n');return c.html(layout('Bot Komutları',`<div class="card"><h2>${esc(b.name)} komutları</h2><form class="form" method="post" action="/bots/${id}/commands"><label>Her satıra bir komut: komut - açıklama</label><textarea class="input" name="commands" rows="12" placeholder="start | Başlangıç mesajı | Hoş geldin!\nhelp | Yardım | Yardım için destek ekibine yazın.">${esc(value)}</textarea><button>Komutları Telegram'a Kaydet</button></form><p class="muted">Her satır: komut | açıklama | kullanıcıya gönderilecek cevap. Örnek: help | Yardım | Destek için yazın. Komutlar Telegram menüsüne eklenir ve gelen /komut mesajına cevap verir.</p><a class="btn gray" href="/bots/${id}">Bota dön</a></div>`))})
app.post('/bots/:id/commands',async c=>{const id=Number(c.req.param('id'));const b:any=await c.env.DB.prepare('SELECT * FROM bots WHERE id=?').bind(id).first();if(!b)return c.text('Bot bulunamadı',404);const f=await c.req.parseBody();const raw=String(f.commands||'');const cmds:any[]=[];for(const line of raw.split(/\r?\n/)){const clean=line.trim();if(!clean)continue;const parts=clean.split(/\s+\|\s+/,3);const command=String(parts[0]||'').replace(/^\//,'').trim();const description=String(parts[1]||command).trim();const response=String(parts[2]||'').trim();if(!/^[a-z0-9_]{1,32}$/.test(command)||!description||description.length>256)continue;if(!cmds.some(x=>x.command===command))cmds.push({command,description,response});}if(cmds.length>100)return c.text('En fazla 100 komut kaydedilebilir',400);const result:any=await tg(b.token,'setMyCommands',{commands:cmds});if(!result.ok){await c.env.DB.prepare('UPDATE bots SET last_error=? WHERE id=?').bind(result.description||'setMyCommands başarısız',id).run();return c.html(layout('Komut Hatası',`<div class="notice">Telegram komutları kaydedemedi: ${esc(result.description||'Bilinmeyen hata')}</div><a class="btn" href="/bots/${id}/commands">Geri dön</a>`),400)}await c.env.DB.prepare('DELETE FROM bot_commands WHERE bot_id=?').bind(id).run();for(const x of cmds)await c.env.DB.prepare('INSERT INTO bot_commands(bot_id,command,description,response_text) VALUES(?,?,?,?)').bind(id,x.command,x.description,x.response).run();await c.env.DB.prepare('UPDATE bots SET last_error=NULL,updated_at=? WHERE id=?').bind(new Date().toISOString(),id).run();await log(c,'COMMANDS_UPDATE',`${id}:${cmds.length}`);return c.redirect(`/bots/${id}/commands`)})
app.get('/bots/:id/buttons',async c=>{const id=Number(c.req.param('id'));const b:any=await c.env.DB.prepare('SELECT * FROM bots WHERE id=?').bind(id).first();if(!b)return c.text('Bot bulunamadı',404);const rows:any[]=await c.env.DB.prepare('SELECT * FROM reply_buttons WHERE bot_id=? ORDER BY row_number,position').bind(id).all().then(x=>x.results as any[]);const value=rows.map(x=>`${x.text} | ${x.url}`).join('\n');return c.html(layout('Start Butonları',`<div class="card"><h2>${esc(b.name)} butonları</h2><form class="form" method="post" action="/bots/${id}/buttons"><label>Her satır: Buton yazısı | https://adres</label><textarea class="input" name="buttons" rows="10" placeholder="Siteye Git | https://example.com\nDestek | https://t.me/example">${esc(value)}</textarea><button>Butonları Kaydet</button></form><p class="muted">Bu butonlar /start mesajının altında görünür. Kaydetmek mevcut buton listesini değiştirir.</p><a class="btn gray" href="/bots/${id}">Bota dön</a></div>`))})
app.post('/bots/:id/buttons',async c=>{const id=Number(c.req.param('id'));const b:any=await c.env.DB.prepare('SELECT id FROM bots WHERE id=?').bind(id).first();if(!b)return c.text('Bot bulunamadı',404);const f=await c.req.parseBody();const lines=String(f.buttons||'').split(/\r?\n/);const items:any[]=[];for(const line of lines){const parts=line.split('|');const text=String(parts.shift()||'').trim();const url=String(parts.join('|')||'').trim();if(!text&&!url)continue;if(!text||!/^https:\/\//i.test(url))continue;if(items.length<50)items.push({text:text.slice(0,64),url});}await c.env.DB.prepare('DELETE FROM reply_buttons WHERE bot_id=?').bind(id).run();for(let i=0;i<items.length;i++)await c.env.DB.prepare('INSERT INTO reply_buttons(bot_id,text,url,row_number,position) VALUES(?,?,?,?,?)').bind(id,items[i].text,items[i].url,Math.floor(i/2),i%2).run();await log(c,'BUTTONS_UPDATE',`${id}:${items.length}`);return c.redirect(`/bots/${id}/buttons`)})
}
